### PR TITLE
Removed single quotes which cause MoveIt tutorial to fail on Windows

### PR DESCRIPTION
**Pull request by lilustga**

### CODE REVIEW

**Comment by rhaschke** [comment]
Single quotes are required on Linux (and I guess on Windows too) to handle spaces in path names. As we cannot know the name of the catkin workspace a user has created, we should handle this case.
How do you handle filenames with spaces in Windows?

**Comment by lilustga** [comment]
@rhaschke I tested double quotes on both Windows and Linux. I believe that should fix the regression with spaces in names as well.

**Comment by rhaschke** [comment]
This might work, but it is really ugly like this. May I ask, what the original error is that you observed?
Is XML parsing failing or roslaunch handling the filename? Maybe it would be better to tackle those issues.

**Comment by lilustga** [comment]
On Windows the command is being sent to cmd.exe which treats single quotes differently and cannot find the file. Nesting double quotes works in both Windows and Linux and handles spaces. However, as far as I'm aware nesting double quotes in XML can only be done with `&quot;`.

Any Ideas on how to resolve this?

**Comment by rhaschke** [comment]
Instead of adapting a lot of launch files (I guess not only MoveIt is affected), I suggest adapting roslaunch on Windows to replace single quotes with double quotes before launching cmd.exe.

**Comment by seanyen** [comment]
> Instead of adapting a lot of launch files (I guess not only MoveIt is affected), I suggest adapting roslaunch on Windows to replace single quotes with double quotes before launching cmd.exe.

One idea could be doing some fix-ups when `roslaunch` tokenizes the `command`, where we can try to patch the tokens if it is surrounded by single quotes.
https://github.com/ros/ros_comm/blob/12eaf946597739e833b2300ef28bb079f248a9e1/tools/roslaunch/src/roslaunch/loader.py#L503

Just my two cents.

**Pull request closed without merging**
