### PR TITLE
demo_chomp.launch: reuse demo.launch

### PR DESCRIPTION
**Pull request by rhaschke**
Reduce code duplication but reuse demo.launch for demo_chomp.launch.
Actually, the chomp demo can be started via:
`roslaunch panda_moveit_config demo.launch pipeline:=chomp`

This PR  replaces #55, which was attempting to remove inconsistencies between demo.launch and demo_chomp.launch.

### CODE REVIEW

**Comment by jsbyysheng** [comment]
What about integrating `OMPL-CHOMP processor` into `demo.launch` and the demo in chomp can be started through `roslaunch panda_moveit_config demo.launch pipeline:=ompl-chomp`? [#463 in moveit tutorial](https://github.com/ros-planning/moveit_tutorials/pull/463)

**Comment by rhaschke** [comment]
That's fine with me as well. I will augment the https://github.com/ros-planning/moveit_tutorials/pull/464 appropriately.

**Comment by rhaschke** [comment]
@jsbyysheng, you are welcome to test the proposed solution.

**Comment by jsbyysheng** [comment]
> @jsbyysheng, you are welcome to test the proposed solution.

My pleasure. After executing `roslaunch panda_moveit_config demo.launch pipeline:=ompl-chomp`, it works well as below:
```
[ INFO] [1582795411.728052410]: Planning request received for MoveGroup action. Forwarding to planning pipeline.                                                                                              
[ INFO] [1582795411.729638050]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.                  
[ INFO] [1582795411.730199909]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure                                                                                                 
[ INFO] [1582795411.730237132]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure                                                                                                 
[ INFO] [1582795411.730275249]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure                                                                                                 
[ INFO] [1582795411.730316515]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure                                                                                                 
[ INFO] [1582795411.741358634]: panda_arm/panda_arm: Created 4 states (2 start + 2 goal)                                                                                                                      
[ INFO] [1582795411.741569805]: panda_arm/panda_arm: Created 4 states (2 start + 2 goal) 
[ INFO] [1582795411.741616921]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.741944185]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.742030821]: ParallelPlan::solve(): Solution found by one or more threads in 0.012090 seconds
[ INFO] [1582795411.742264408]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1582795411.743477434]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.744577661]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1582795411.744650841]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1582795411.745489784]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.745599921]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1582795411.745645083]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.746470971]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.746566282]: ParallelPlan::solve(): Solution found by one or more threads in 0.004433 seconds
[ INFO] [1582795411.746703492]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1582795411.746738118]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1582795411.748020830]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.748066876]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1582795411.748182497]: ParallelPlan::solve(): Solution found by one or more threads in 0.001543 seconds
[ INFO] [1582795411.751573377]: SimpleSetup: Path simplification took 0.003267 seconds and changed from 3 to 2 states
[ INFO] [1582795411.988817061]: CHOMP trajectory initialized using method: fillTrajectory
[ INFO] [1582795411.988903144]: The following collision detectors are available in the planning scene.
[ INFO] [1582795411.988920438]: HYBRID
[ INFO] [1582795411.988940421]: Active collision detector is: HYBRID
[ INFO] [1582795412.087337112]: First coll check took 0.098350938
[ INFO] [1582795412.103858757]: iteration: 0
[ INFO] [1582795412.106119835]: Chomp Got mesh to mesh safety at iter 0. Breaking out early.
[ INFO] [1582795412.106160830]: Chomp path is collision free
[ INFO] [1582795412.106195432]: Terminated after 1 iterations, using path from iteration 0
[ INFO] [1582795412.106220846]: Optimization core finished in 0.005867 sec
[ INFO] [1582795412.106244250]: Time per iteration 0.0058888
```

**Pull request merged**
